name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Render
        run: |
          curl -o /usr/local/bin/render https://raw.githubusercontent.com/render-community/render-cli/main/render
          chmod +x /usr/local/bin/render
          render login --api-key ${{ secrets.RENDER_API_KEY }}

      - name: Deploy Web Service
        run: |
          render deploy web service ${{ vars.RENDER_SERVICE_ID }}